# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_hello.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_miscdev.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_miscdev_box.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_miscdev_read.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_refcounted.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_miscdev_arc.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_miscdev_arc_read.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_miscdev_write.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_miscdev_global.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_thread.o
obj-$(CONFIG_SAMPLE_LKP_RUST)	+= lkp_sync.o
