# SPDX-License-Identifier: GPL-2.0

CFLAGS += -I../../../../usr/include/
CFLAGS += -g
CFLAGS += -D_GNU_SOURCE
CFLAGS += -Wall
CFLAGS += -pthread
CFLAGS += -static

TEST_GEN_PROGS := ping_server ping_client

include ../lib.mk
